export const company_mock_data = [
    {
        job_id: 'iu3ju0hdiz',
        job_role: 'Software Development-2',
        company_name: 'Microsoft',
        location: 'Delhi',
        work_mode: 'in-office',
        job_offer: '80k-120k',
        company_size: '100,000+ Employees',
        logo: "company_logo",
        start_date: '10/06/2024',
        experience: '2-4 Years',
        last_date: '05/03/2024',
        probation_period: '3 months',
        skills: ['React', 'Node.js', 'Azure', 'Git', 'SQL'],
        requirement: ['Design, code, debug, and unit test Android mobile applications',
            'Connecting with the product team to understand the features/business requirements for Android app development',
            'Integrate third-party services, such as REST APIs and Firebase',
            'Able to Work on Live Data and Good at Layout Design',
            'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
            'Assisting in the documentation and version control of app development processes',
            'Experience with third-party libraries and APIs'
        ],
        perks_benefit: [
            'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
            'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
            'We have an interesting culture where team members share info',
            'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
            'We respect your suggestion & feedback to improve both technical & non technical end.'
        ],
        eligibility: [
            'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
            'Should have a bachelor degree in computer science',
            'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
            'At least 2 years of professional experience in Mobile App Development or related field',
            'Strong knowledge of Java or Kotlin for Android application development',
            'Good understanding of MVC architecture design pattern',
            'Hands-on experience with SQL database management system'
        ],
        joining_date: 'Immediate'
    },
    {
        job_id: 'kio46vdgye9',
        job_role: 'Quality Assurance',
        company_name: 'Google',
        location: 'Gurgaon',
        work_mode: 'hybrid',
        job_offer: '90k-130k',
        company_size: '150,000+ Employees',
        logo: "company_logo",
        start_date: '02/02/2024',
        experience: '0-2 Years',
        last_date: '10/03/2024',
        probation_period: '4 months',
        skills: ['Angular', 'Python', 'Django', 'Git', 'Java'],
        requirement: ['Design, code, debug, and unit test Android mobile applications',
            'Connecting with the product team to understand the features/business requirements for Android app development',
            'Integrate third-party services, such as REST APIs and Firebase',
            'Able to Work on Live Data and Good at Layout Design',
            'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
            'Assisting in the documentation and version control of app development processes',
            'Experience with third-party libraries and APIs'
        ],
        perks_benefit: [
            'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
            'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
            'We have an interesting culture where team members share info',
            'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
            'We respect your suggestion & feedback to improve both technical & non technical end.'
        ],
        eligibility: [
            'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
            'Should have a bachelor degree in computer science',
            'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
            'At least 2 years of professional experience in Mobile App Development or related field',
            'Strong knowledge of Java or Kotlin for Android application development',
            'Good understanding of MVC architecture design pattern',
            'Hands-on experience with SQL database management system'
        ],
        joining_date: 'Immediate'
    },
    {
        job_id: '6gdt8gd2m9',
        job_role: 'Full-stack Developer',
        company_name: 'Amazon',
        location: 'Noida',
        work_mode: 'remote',
        job_offer: '100k-150k',
        company_size: '500,000+ Employees',
        logo: "company_logo",
        start_date: '05/02/2024',
        experience: '0-2 Years',
        last_date: '15/03/2024',
        probation_period: '2 months',
        skills: ['React', 'Java', 'AWS', 'Git', 'DynamoDB'],
        requirement: ['Design, code, debug, and unit test Android mobile applications',
            'Connecting with the product team to understand the features/business requirements for Android app development',
            'Integrate third-party services, such as REST APIs and Firebase',
            'Able to Work on Live Data and Good at Layout Design',
            'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
            'Assisting in the documentation and version control of app development processes',
            'Experience with third-party libraries and APIs'
        ],
        perks_benefit: [
            'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
            'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
            'We have an interesting culture where team members share info',
            'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
            'We respect your suggestion & feedback to improve both technical & non technical end.'
        ],
        eligibility: [
            'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
            'Should have a bachelor degree in computer science',
            'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
            'At least 2 years of professional experience in Mobile App Development or related field',
            'Strong knowledge of Java or Kotlin for Android application development',
            'Good understanding of MVC architecture design pattern',
            'Hands-on experience with SQL database management system'
        ],
        joining_date: 'Immediate'
    },
    {
        job_id: '9ie4mjkfct',
        job_role: 'Software Engineer-2',
        company_name: 'Facebook',
        location: 'Hyderabad',
        work_mode: 'in-office',
        job_offer: '120k-180k',
        company_size: '75,000+ Employees',
        logo: "company_logo",
        start_date: '01/03/2024',
        experience: '4-6 Years',
        last_date: '20/03/2024',
        probation_period: '3 months',
        skills: ['React', 'PHP', 'Hack', 'Git', 'MySQL'],
        requirement: ['Design, code, debug, and unit test Android mobile applications',
            'Connecting with the product team to understand the features/business requirements for Android app development',
            'Integrate third-party services, such as REST APIs and Firebase',
            'Able to Work on Live Data and Good at Layout Design',
            'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
            'Assisting in the documentation and version control of app development processes',
            'Experience with third-party libraries and APIs'
        ],
        perks_benefit: [
            'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
            'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
            'We have an interesting culture where team members share info',
            'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
            'We respect your suggestion & feedback to improve both technical & non technical end.'
        ],
        eligibility: [
            'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
            'Should have a bachelor degree in computer science',
            'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
            'At least 2 years of professional experience in Mobile App Development or related field',
            'Strong knowledge of Java or Kotlin for Android application development',
            'Good understanding of MVC architecture design pattern',
            'Hands-on experience with SQL database management system'
        ],
        joining_date: 'Immediate'
    },
    {
        job_id: 'p7evg7dv0b',
        job_role: 'IOS Developer-2',
        company_name: 'Apple',
        location: 'Bangalore',
        work_mode: 'hybrid',
        job_offer: '110k-160k',
        company_size: '150,000+ Employees',
        logo: "company_logo",
        start_date: '05/03/2024',
        experience: '2-4 Years',
        last_date: '25/03/2024',
        probation_period: '2 months',
        skills: ['Swift', 'Objective-C', 'iOS', 'Git', 'Xcode'],
        requirement: ['Design, code, debug, and unit test Android mobile applications',
            'Connecting with the product team to understand the features/business requirements for Android app development',
            'Integrate third-party services, such as REST APIs and Firebase',
            'Able to Work on Live Data and Good at Layout Design',
            'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
            'Assisting in the documentation and version control of app development processes',
            'Experience with third-party libraries and APIs'
        ],
        perks_benefit: [
            'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
            'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
            'We have an interesting culture where team members share info',
            'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
            'We respect your suggestion & feedback to improve both technical & non technical end.'
        ],
        eligibility: [
            'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
            'Should have a bachelor degree in computer science',
            'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
            'At least 2 years of professional experience in Mobile App Development or related field',
            'Strong knowledge of Java or Kotlin for Android application development',
            'Good understanding of MVC architecture design pattern',
            'Hands-on experience with SQL database management system'
        ],
        joining_date: 'Immediate'
    },
    {
        job_id: 'pod3nj9dv9',
        job_role: 'Android Developer',
        company_name: 'Tesla',
        location: 'Kolkata',
        work_mode: 'in-office',
        job_offer: '150k-200k',
        company_size: '50,000+ Employees',
        logo: "company_logo",
        start_date: '10/03/2024',
        experience: 'Fresher',
        last_date: '30/03/2024',
        probation_period: '3 months',
        skills: ['JavaScript', 'Python', 'C++', 'Git', 'Autopilot'],
        requirement: ['Design, code, debug, and unit test Android mobile applications',
            'Connecting with the product team to understand the features/business requirements for Android app development',
            'Integrate third-party services, such as REST APIs and Firebase',
            'Able to Work on Live Data and Good at Layout Design',
            'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
            'Assisting in the documentation and version control of app development processes',
            'Experience with third-party libraries and APIs'
        ],
        perks_benefit: [
            'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
            'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
            'We have an interesting culture where team members share info',
            'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
            'We respect your suggestion & feedback to improve both technical & non technical end.'
        ],
        eligibility: [
            'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
            'Should have a bachelor degree in computer science',
            'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
            'At least 2 years of professional experience in Mobile App Development or related field',
            'Strong knowledge of Java or Kotlin for Android application development',
            'Good understanding of MVC architecture design pattern',
            'Hands-on experience with SQL database management system'
        ],
        joining_date: 'Immediate'
    },
    {
        job_id: '8gv0o1hstb',
        job_role: 'Frontend Developer',
        company_name: 'Netflix',
        location: 'Delhi',
        work_mode: 'remote',
        job_offer: '130k-180k',
        company_size: '10,000+ Employees',
        logo: "company_logo",
        start_date: '09/03/2024',
        experience: '0-1 Years',
        last_date: '05/04/2024',
        probation_period: '2 months',
        skills: ['React', 'Java', 'Spring', 'Git', 'Microservices'],
        requirement: ['Design, code, debug, and unit test Android mobile applications',
            'Connecting with the product team to understand the features/business requirements for Android app development',
            'Integrate third-party services, such as REST APIs and Firebase',
            'Able to Work on Live Data and Good at Layout Design',
            'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
            'Assisting in the documentation and version control of app development processes',
            'Experience with third-party libraries and APIs'
        ],
        perks_benefit: [
            'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
            'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
            'We have an interesting culture where team members share info',
            'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
            'We respect your suggestion & feedback to improve both technical & non technical end.'
        ],
        eligibility: [
            'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
            'Should have a bachelor degree in computer science',
            'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
            'At least 2 years of professional experience in Mobile App Development or related field',
            'Strong knowledge of Java or Kotlin for Android application development',
            'Good understanding of MVC architecture design pattern',
            'Hands-on experience with SQL database management system'
        ],
        joining_date: 'Immediate'
    },
    {
        job_id: '7vu2yvy0ou',
        job_role: 'Fullstack Developer',
        company_name: 'LinkedIn',
        location: 'Gurgaon',
        work_mode: 'hybrid',
        job_offer: '110k-150k',
        company_size: '15,000+ Employees',
        logo: "company_logo",
        start_date: '10/03/2024',
        experience: '1-2 Years',
        last_date: '10/04/2024',
        probation_period: '3 months',
        skills: ['React', 'Node.js', 'Express.js', 'Git', 'MongoDB'],
        requirement: ['Design, code, debug, and unit test Android mobile applications',
            'Connecting with the product team to understand the features/business requirements for Android app development',
            'Integrate third-party services, such as REST APIs and Firebase',
            'Able to Work on Live Data and Good at Layout Design',
            'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
            'Assisting in the documentation and version control of app development processes',
            'Experience with third-party libraries and APIs'
        ],
        perks_benefit: [
            'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
            'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
            'We have an interesting culture where team members share info',
            'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
            'We respect your suggestion & feedback to improve both technical & non technical end.'
        ],
        eligibility: [
            'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
            'Should have a bachelor degree in computer science',
            'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
            'At least 2 years of professional experience in Mobile App Development or related field',
            'Strong knowledge of Java or Kotlin for Android application development',
            'Good understanding of MVC architecture design pattern',
            'Hands-on experience with SQL database management system'
        ],
        joining_date: 'Immediate'
    },
    {
        job_id: 'poi35vc80m3',
        job_role: 'Backend Developer',
        company_name: 'Uber',
        location: 'Noida',
        work_mode: 'in-office',
        job_offer: '120k-170k',
        company_size: '20,000+ Employees',
        logo: "company_logo",
        start_date: '08/03/2024',
        experience: '0-2 Years',
        last_date: '15/04/2024',
        probation_period: '2 months',
        skills: ['React', 'Node.js', 'Python', 'Git', 'RESTful APIs'],
        requirement: ['Design, code, debug, and unit test Android mobile applications',
            'Connecting with the product team to understand the features/business requirements for Android app development',
            'Integrate third-party services, such as REST APIs and Firebase',
            'Able to Work on Live Data and Good at Layout Design',
            'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
            'Assisting in the documentation and version control of app development processes',
            'Experience with third-party libraries and APIs'
        ],
        perks_benefit: [
            'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
            'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
            'We have an interesting culture where team members share info',
            'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
            'We respect your suggestion & feedback to improve both technical & non technical end.'
        ],
        eligibility: [
            'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
            'Should have a bachelor degree in computer science',
            'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
            'At least 2 years of professional experience in Mobile App Development or related field',
            'Strong knowledge of Java or Kotlin for Android application development',
            'Good understanding of MVC architecture design pattern',
            'Hands-on experience with SQL database management system'
        ],
        joining_date: 'Immediate'
    },
    {
        job_id: 'poevu9d8h3',
        job_role: 'IOS Developer',
        company_name: 'Twitter',
        location: 'Delhi',
        work_mode: 'remote',
        job_offer: '100k-140k',
        company_size: '5,000+ Employees',
        logo: "company_logo",
        start_date: '01/04/2024',
        experience: '2-3 Years',
        last_date: '20/04/2024',
        probation_period: '3 months',
        skills: ['React', 'Java', 'Spring Boot', 'Git', 'Kafka'],
        requirement: ['Design, code, debug, and unit test Android mobile applications',
            'Connecting with the product team to understand the features/business requirements for Android app development',
            'Integrate third-party services, such as REST APIs and Firebase',
            'Able to Work on Live Data and Good at Layout Design',
            'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
            'Assisting in the documentation and version control of app development processes',
            'Experience with third-party libraries and APIs'
        ],
        perks_benefit: [
            'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
            'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
            'We have an interesting culture where team members share info',
            'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
            'We respect your suggestion & feedback to improve both technical & non technical end.'
        ],
        eligibility: [
            'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
            'Should have a bachelor degree in computer science',
            'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
            'At least 2 years of professional experience in Mobile App Development or related field',
            'Strong knowledge of Java or Kotlin for Android application development',
            'Good understanding of MVC architecture design pattern',
            'Hands-on experience with SQL database management system'
        ],
        joining_date: 'Immediate'
    },
    {
        job_id: '9eic83bh4c',
        job_role: 'Portal Engineer-2',
        company_name: 'Salesforce',
        location: 'Gurgaon',
        work_mode: 'hybrid',
        job_offer: '130k-180k',
        company_size: '50,000+ Employees',
        logo: "company_logo",
        start_date: '05/04/2024',
        experience: '2-4 Years',
        last_date: '25/04/2024',
        probation_period: '2 months',
        skills: ['React', 'Apex', 'Salesforce Lightning', 'Git', 'SQL'],
        requirement: ['Design, code, debug, and unit test Android mobile applications',
            'Connecting with the product team to understand the features/business requirements for Android app development',
            'Integrate third-party services, such as REST APIs and Firebase',
            'Able to Work on Live Data and Good at Layout Design',
            'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
            'Assisting in the documentation and version control of app development processes',
            'Experience with third-party libraries and APIs'
        ],
        perks_benefit: [
            'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
            'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
            'We have an interesting culture where team members share info',
            'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
            'We respect your suggestion & feedback to improve both technical & non technical end.'
        ],
        eligibility: [
            'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
            'Should have a bachelor degree in computer science',
            'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
            'At least 2 years of professional experience in Mobile App Development or related field',
            'Strong knowledge of Java or Kotlin for Android application development',
            'Good understanding of MVC architecture design pattern',
            'Hands-on experience with SQL database management system'
        ],
        joining_date: 'Immediate'
    },
    {
        job_id: 'h7gd03hw9c',
        job_role: 'React Developer',
        company_name: 'Adobe',
        location: 'Noida',
        work_mode: 'in-office',
        job_offer: '110k-160k',
        company_size: '20,000+ Employees',
        logo: "company_logo",
        start_date: '10/04/2024',
        experience: '0-2 Years',
        last_date: '30/04/2024',
        probation_period: '3 months',
        skills: ['React', 'Node.js', 'JavaScript', 'Git', 'Photoshop'],
        requirement: ['Design, code, debug, and unit test Android mobile applications',
            'Connecting with the product team to understand the features/business requirements for Android app development',
            'Integrate third-party services, such as REST APIs and Firebase',
            'Able to Work on Live Data and Good at Layout Design',
            'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
            'Assisting in the documentation and version control of app development processes',
            'Experience with third-party libraries and APIs'
        ],
        perks_benefit: [
            'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
            'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
            'We have an interesting culture where team members share info',
            'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
            'We respect your suggestion & feedback to improve both technical & non technical end.'
        ],
        eligibility: [
            'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
            'Should have a bachelor degree in computer science',
            'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
            'At least 2 years of professional experience in Mobile App Development or related field',
            'Strong knowledge of Java or Kotlin for Android application development',
            'Good understanding of MVC architecture design pattern',
            'Hands-on experience with SQL database management system'
        ],
        joining_date: 'Immediate'
    },
    {
        job_id: 'p3vtc8bcy6',
        job_role: 'AI Engineer',
        company_name: 'Intel',
        location: 'Hyderabad',
        work_mode: 'remote',
        job_offer: '120k-170k',
        company_size: '50,000+ Employees',
        logo: "company_logo",
        start_date: '05/04/2024',
        experience: '6-10 Years',
        last_date: '05/05/2024',
        probation_period: '2 months',
        skills: ['C++', 'Java', 'Python', 'Git', 'Machine Learning'],
        requirement: ['Design, code, debug, and unit test Android mobile applications',
            'Connecting with the product team to understand the features/business requirements for Android app development',
            'Integrate third-party services, such as REST APIs and Firebase',
            'Able to Work on Live Data and Good at Layout Design',
            'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
            'Assisting in the documentation and version control of app development processes',
            'Experience with third-party libraries and APIs'
        ],
        perks_benefit: [
            'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
            'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
            'We have an interesting culture where team members share info',
            'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
            'We respect your suggestion & feedback to improve both technical & non technical end.'
        ],
        eligibility: [
            'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
            'Should have a bachelor degree in computer science',
            'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
            'At least 2 years of professional experience in Mobile App Development or related field',
            'Strong knowledge of Java or Kotlin for Android application development',
            'Good understanding of MVC architecture design pattern',
            'Hands-on experience with SQL database management system'
        ],
        joining_date: 'Immediate'
    },
    {
        job_id: 'vdt87cyt01',
        job_role: 'Cloud Architect-4',
        company_name: 'IBM',
        location: 'Bangalore',
        work_mode: 'in-office',
        job_offer: '130k-180k',
        company_size: '300,000+ Employees',
        logo: "company_logo",
        start_date: '02/04/2024',
        experience: '5-9 Years',
        last_date: '10/05/2024',
        probation_period: '3 months',
        skills: ['Java', 'Python', 'IBM Cloud', 'Git', 'SQL'],
        requirement: ['Design, code, debug, and unit test Android mobile applications',
            'Connecting with the product team to understand the features/business requirements for Android app development',
            'Integrate third-party services, such as REST APIs and Firebase',
            'Able to Work on Live Data and Good at Layout Design',
            'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
            'Assisting in the documentation and version control of app development processes',
            'Experience with third-party libraries and APIs'
        ],
        perks_benefit: [
            'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
            'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
            'We have an interesting culture where team members share info',
            'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
            'We respect your suggestion & feedback to improve both technical & non technical end.'
        ],
        eligibility: [
            'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
            'Should have a bachelor degree in computer science',
            'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
            'At least 2 years of professional experience in Mobile App Development or related field',
            'Strong knowledge of Java or Kotlin for Android application development',
            'Good understanding of MVC architecture design pattern',
            'Hands-on experience with SQL database management system'
        ],
        joining_date: 'Immediate'
    },
    {
        job_id: 'fd6bh8e9d0',
        job_role: 'Network Engineer',
        company_name: 'Cisco',
        location: 'Kolkata',
        work_mode: 'hybrid',
        job_offer: '110k-150k',
        company_size: '70,000+ Employees',
        logo: "company_logo",
        start_date: '25/04/2024',
        experience: '4-8 Years',
        last_date: '15/05/2024',
        probation_period: '2 months',
        skills: ['Networking', 'Python', 'Cisco IOS', 'Git', 'CCNA'],
        requirement: ['Design, code, debug, and unit test Android mobile applications',
            'Connecting with the product team to understand the features/business requirements for Android app development',
            'Integrate third-party services, such as REST APIs and Firebase',
            'Able to Work on Live Data and Good at Layout Design',
            'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
            'Assisting in the documentation and version control of app development processes',
            'Experience with third-party libraries and APIs'
        ],
        perks_benefit: [
            'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
            'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
            'We have an interesting culture where team members share info',
            'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
            'We respect your suggestion & feedback to improve both technical & non technical end.'
        ],
        eligibility: [
            'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
            'Should have a bachelor degree in computer science',
            'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
            'At least 2 years of professional experience in Mobile App Development or related field',
            'Strong knowledge of Java or Kotlin for Android application development',
            'Good understanding of MVC architecture design pattern',
            'Hands-on experience with SQL database management system'
        ],
        joining_date: 'Immediate'
    },
    {
        job_id: 'vy50x8n7e0',
        job_role: 'Game Developer',
        company_name: 'HP',
        location: 'Delhi',
        work_mode: 'remote',
        job_offer: '120k-170k',
        company_size: '50,000+ Employees',
        logo: "company_logo",
        start_date: '01/05/2024',
        experience: '6-10 Years',
        last_date: '20/05/2024',
        probation_period: '3 months',
        skills: ['Java', 'C#', '.NET', 'Git', 'Printer Drivers'],
        requirement: ['Design, code, debug, and unit test Android mobile applications',
            'Connecting with the product team to understand the features/business requirements for Android app development',
            'Integrate third-party services, such as REST APIs and Firebase',
            'Able to Work on Live Data and Good at Layout Design',
            'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
            'Assisting in the documentation and version control of app development processes',
            'Experience with third-party libraries and APIs'
        ],
        perks_benefit: [
            'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
            'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
            'We have an interesting culture where team members share info',
            'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
            'We respect your suggestion & feedback to improve both technical & non technical end.'
        ],
        eligibility: [
            'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
            'Should have a bachelor degree in computer science',
            'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
            'At least 2 years of professional experience in Mobile App Development or related field',
            'Strong knowledge of Java or Kotlin for Android application development',
            'Good understanding of MVC architecture design pattern',
            'Hands-on experience with SQL database management system'
        ],
        joining_date: 'Immediate'
    },
    {
        job_id: 'yvct67k97v',
        job_role: 'Database Engineer',
        company_name: 'Oracle',
        location: 'Gurgaon',
        work_mode: 'in-office',
        job_offer: '140k-200k',
        company_size: '100,000+ Employees',
        logo: "company_logo",
        start_date: '05/05/2024',
        experience: '8-12 Years',
        last_date: '25/05/2024',
        probation_period: '2 months',
        skills: ['Java', 'PL/SQL', 'Oracle Database', 'Git', 'SQL'],
        requirement: ['Design, code, debug, and unit test Android mobile applications',
            'Connecting with the product team to understand the features/business requirements for Android app development',
            'Integrate third-party services, such as REST APIs and Firebase',
            'Able to Work on Live Data and Good at Layout Design',
            'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
            'Assisting in the documentation and version control of app development processes',
            'Experience with third-party libraries and APIs'
        ],
        perks_benefit: [
            'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
            'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
            'We have an interesting culture where team members share info',
            'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
            'We respect your suggestion & feedback to improve both technical & non technical end.'
        ],
        eligibility: [
            'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
            'Should have a bachelor degree in computer science',
            'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
            'At least 2 years of professional experience in Mobile App Development or related field',
            'Strong knowledge of Java or Kotlin for Android application development',
            'Good understanding of MVC architecture design pattern',
            'Hands-on experience with SQL database management system'
        ],
        joining_date: 'Immediate'
    },
    {
        job_id: '78bgy9f6gb',
        job_role: '.Net Developer-2',
        company_name: 'Dell',
        location: 'Noida',
        work_mode: 'hybrid',
        job_offer: '130k-180k',
        company_size: '150,000+ Employees',
        logo: "company_logo",
        start_date: '10/05/2024',
        experience: '2-4 Years',
        last_date: '30/05/2024',
        probation_period: '3 months',
        skills: ['C#', 'JavaScript', '.NET', 'Git', 'Dell EMC'],
        requirement: ['Design, code, debug, and unit test Android mobile applications',
            'Connecting with the product team to understand the features/business requirements for Android app development',
            'Integrate third-party services, such as REST APIs and Firebase',
            'Able to Work on Live Data and Good at Layout Design',
            'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
            'Assisting in the documentation and version control of app development processes',
            'Experience with third-party libraries and APIs'
        ],
        perks_benefit: [
            'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
            'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
            'We have an interesting culture where team members share info',
            'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
            'We respect your suggestion & feedback to improve both technical & non technical end.'
        ],
        eligibility: [
            'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
            'Should have a bachelor degree in computer science',
            'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
            'At least 2 years of professional experience in Mobile App Development or related field',
            'Strong knowledge of Java or Kotlin for Android application development',
            'Good understanding of MVC architecture design pattern',
            'Hands-on experience with SQL database management system'
        ],
        joining_date: 'Immediate'
    },
    {
        job_id: 'y63hy0eb9c',
        job_role: 'Machine Learning Engineer',
        company_name: 'NVIDIA',
        location: 'Hyderabad',
        work_mode: 'remote',
        job_offer: '150k-220k',
        company_size: '20,000+ Employees',
        logo: "company_logo",
        start_date: '15/05/2024',
        experience: '2-4 Years',
        last_date: '05/06/2024',
        probation_period: '2 months',
        skills: ['C++', 'CUDA', 'Machine Learning', 'Git', 'Graphics Programming'],
        requirement: ['Design, code, debug, and unit test Android mobile applications',
            'Connecting with the product team to understand the features/business requirements for Android app development',
            'Integrate third-party services, such as REST APIs and Firebase',
            'Able to Work on Live Data and Good at Layout Design',
            'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
            'Assisting in the documentation and version control of app development processes',
            'Experience with third-party libraries and APIs'
        ],
        perks_benefit: [
            'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
            'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
            'We have an interesting culture where team members share info',
            'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
            'We respect your suggestion & feedback to improve both technical & non technical end.'
        ],
        eligibility: [
            'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
            'Should have a bachelor degree in computer science',
            'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
            'At least 2 years of professional experience in Mobile App Development or related field',
            'Strong knowledge of Java or Kotlin for Android application development',
            'Good understanding of MVC architecture design pattern',
            'Hands-on experience with SQL database management system'
        ],
        joining_date: 'Immediate'
    },
    {
        job_id: '6tf83i8vu7',
        job_role: 'Databse Engineer-4',
        company_name: 'VMware',
        location: 'Kolkata',
        work_mode: 'in-office',
        job_offer: '140k-190k',
        company_size: '30,000+ Employees',
        logo: "company_logo",
        start_date: '20/05/2024',
        experience: '6-10 Years',
        last_date: '10/06/2024',
        probation_period: '3 months',
        skills: ['Java', 'Python', 'VMware vSphere', 'Git', 'Virtualization'],
        requirement: ['Design, code, debug, and unit test Android mobile applications',
            'Connecting with the product team to understand the features/business requirements for Android app development',
            'Integrate third-party services, such as REST APIs and Firebase',
            'Able to Work on Live Data and Good at Layout Design',
            'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
            'Assisting in the documentation and version control of app development processes',
            'Experience with third-party libraries and APIs'
        ],
        perks_benefit: [
            'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
            'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
            'We have an interesting culture where team members share info',
            'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
            'We respect your suggestion & feedback to improve both technical & non technical end.'
        ],
        eligibility: [
            'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
            'Should have a bachelor degree in computer science',
            'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
            'At least 2 years of professional experience in Mobile App Development or related field',
            'Strong knowledge of Java or Kotlin for Android application development',
            'Good understanding of MVC architecture design pattern',
            'Hands-on experience with SQL database management system'
        ],
        joining_date: 'Immediate'
    },
    {
        job_id: 'uyh7gy6dv7',
        job_role: 'DevOps Engineer-4',
        company_name: 'Accenture',
        location: 'Delhi',
        work_mode: 'hybrid',
        job_offer: '120k-170k',
        company_size: '500,000+ Employees',
        logo: "company_logo",
        start_date: '25/05/2024',
        experience: '5-9 Years',
        last_date: '15/06/2024',
        probation_period: '2 months',
        skills: ['Java', 'Spring Boot', 'Microservices', 'Git', 'DevOps'],
        requirement: ['Design, code, debug, and unit test Android mobile applications',
            'Connecting with the product team to understand the features/business requirements for Android app development',
            'Integrate third-party services, such as REST APIs and Firebase',
            'Able to Work on Live Data and Good at Layout Design',
            'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
            'Assisting in the documentation and version control of app development processes',
            'Experience with third-party libraries and APIs'
        ],
        perks_benefit: [
            'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
            'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
            'We have an interesting culture where team members share info',
            'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
            'We respect your suggestion & feedback to improve both technical & non technical end.'
        ],
        eligibility: [
            'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
            'Should have a bachelor degree in computer science',
            'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
            'At least 2 years of professional experience in Mobile App Development or related field',
            'Strong knowledge of Java or Kotlin for Android application development',
            'Good understanding of MVC architecture design pattern',
            'Hands-on experience with SQL database management system'
        ],
        joining_date: 'Immediate'
    },
    {
        job_id: '9ubyt94ft5',
        job_role: 'ERP Engineer',
        company_name: 'SAP',
        location: 'Gurgaon',
        work_mode: 'remote',
        job_offer: '130k-180k',
        company_size: '100,000+ Employees',
        logo: "company_logo",
        start_date: '01/06/2024',
        experience: '6-10 Years',
        last_date: '20/06/2024',
        probation_period: '3 months',
        skills: ['ABAP', 'SAP HANA', 'UI5', 'Git', 'ERP'],
        requirement: ['Design, code, debug, and unit test Android mobile applications',
            'Connecting with the product team to understand the features/business requirements for Android app development',
            'Integrate third-party services, such as REST APIs and Firebase',
            'Able to Work on Live Data and Good at Layout Design',
            'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
            'Assisting in the documentation and version control of app development processes',
            'Experience with third-party libraries and APIs'
        ],
        perks_benefit: [
            'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
            'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
            'We have an interesting culture where team members share info',
            'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
            'We respect your suggestion & feedback to improve both technical & non technical end.'
        ],
        eligibility: [
            'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
            'Should have a bachelor degree in computer science',
            'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
            'At least 2 years of professional experience in Mobile App Development or related field',
            'Strong knowledge of Java or Kotlin for Android application development',
            'Good understanding of MVC architecture design pattern',
            'Hands-on experience with SQL database management system'
        ],
        joining_date: 'Immediate'
    },
    {
        job_id: 'hyd89b73b9',
        job_role: 'Java Developer',
        company_name: 'Capgemini',
        location: 'Noida',
        work_mode: 'in-office',
        job_offer: '110k-150k',
        company_size: '200,000+ Employees',
        logo: "company_logo",
        start_date: '05/06/2024',
        experience: '0-2 Years',
        last_date: '25/06/2024',
        probation_period: '2 months',
        skills: ['Java', 'Spring', 'Hibernate', 'Git', 'Agile'],
        requirement: ['Design, code, debug, and unit test Android mobile applications',
            'Connecting with the product team to understand the features/business requirements for Android app development',
            'Integrate third-party services, such as REST APIs and Firebase',
            'Able to Work on Live Data and Good at Layout Design',
            'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
            'Assisting in the documentation and version control of app development processes',
            'Experience with third-party libraries and APIs'
        ],
        perks_benefit: [
            'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
            'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
            'We have an interesting culture where team members share info',
            'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
            'We respect your suggestion & feedback to improve both technical & non technical end.'
        ],
        eligibility: [
            'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
            'Should have a bachelor degree in computer science',
            'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
            'At least 2 years of professional experience in Mobile App Development or related field',
            'Strong knowledge of Java or Kotlin for Android application development',
            'Good understanding of MVC architecture design pattern',
            'Hands-on experience with SQL database management system'
        ],
        joining_date: 'Immediate'
    }
];